(function(root){'use strict';
const statuses=['Not Contacted','Draft Ready','Sent','Followed Up','Closed','Do Not Contact'];
const replies=['No Reply','Generic Reply','Personalized Reply','Faculty Encouraged Application','Strong Personalized Reply','Meeting Requested','Not Recruiting'];
const fields=['id','name','university','department','research','hook','evidence','signal','email','url','status','priority','wave','sent','reply','replySummary','meeting','followup','impact','notes','recruiting','verified','subject','draft'];
const csvAliases={'Professor':'name','University':'university','Home Dept / Route':'department','Primary Research Overlap':'research','Best Hook From Your Profile':'hook','Recruiting / Contact Evidence':'evidence','Signal Value':'signal','Email':'email','Source URL':'url','Contact Status':'status','Priority':'priority','Wave':'wave','Date Sent':'sent','Reply Strength':'reply','Reply Summary':'replySummary','Meeting?':'meeting','Follow-up Date':'followup','Application Impact':'impact','Notes':'notes','Recruiting Signal':'recruiting','Research Areas':'areas','Last Verified':'verified','Email Subject':'subject','Email Draft':'draft','Shortlisted':'favorite'};
function key(r){return (r.name+'-'+r.university).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function normalize(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Each faculty record must be an object.');const r={};for(const k of fields)r[k]=typeof input[k]==='string'?input[k].slice(0,k==='draft'?30000:10000):typeof input[k]==='number'?String(input[k]):'';if(!r.name.trim()||!r.university.trim())throw Error('Each faculty record needs a professor name and university.');r.name=r.name.trim();r.university=r.university.trim();r.id=/^[a-z0-9-]+$/.test(r.id)?r.id:key(r);r.status=statuses.includes(r.status)?r.status:'Not Contacted';r.reply=replies.includes(r.reply)?r.reply:'No Reply';r.meeting=r.meeting==='Yes'?'Yes':'No';r.impact=['Unknown','Negative','Neutral','Positive'].includes(r.impact)?r.impact:'Unknown';r.recruiting=r.recruiting||'No Public Signal';r.areas=Array.isArray(input.areas)?input.areas.filter(x=>typeof x==='string').slice(0,15).map(x=>x.slice(0,100)):[];r.favorite=input.favorite===true||input.favorite==='Yes';for(const k of ['sent','followup','verified'])if(r[k]&&!validDate(r[k]))throw Error('Dates must use YYYY-MM-DD: '+r.name+' ('+k+').');return r}
function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s}
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function due(r,date=today()){return !!r.followup&&r.followup<=date&&!['Closed','Do Not Contact'].includes(r.status)}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false; text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else if(quoted)quoted=false;else if(!cell)quoted=true;else cell+=c}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('The CSV contains an unclosed quoted field.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
function fromCSV(text){const parsed=parseCSV(text);if(parsed.length<2)throw Error('The CSV needs a header and at least one faculty row.');const header=parsed.shift().map(x=>x.trim());const known=new Set([...fields,'areas','favorite']);return parsed.map((cells)=>{const r={};header.forEach((h,i)=>{const k=csvAliases[h]||(known.has(h)?h:null);if(k)r[k]=(cells[i]||'').replace(/^\t(?=[=+@-])/,'')});if(r.areas!==undefined)r.areas=r.areas.split('|').map(x=>x.trim()).filter(Boolean);normalize(r);return r})}
function stringifyCSV(rows){const aliases=Object.entries(csvAliases);const quote=s=>'"'+String(s).replace(/"/g,'""')+'"';const safe=s=>/^[\s]*[=+@-]/.test(s)?'\t'+s:s;return '\uFEFF'+[aliases.map(([h])=>quote(h)).join(','),...rows.map(r=>aliases.map(([,k])=>quote(safe(k==='areas'?r.areas.join(' | '):k==='favorite'?(r.favorite?'Yes':'No'):r[k]||''))).join(','))].join('\r\n')}
function merge(existing,incoming){const map=new Map(existing.map(r=>[r.id,normalize(r)]));for(const entry of incoming){const n=normalize(entry);const previous=map.get(n.id)||[...map.values()].find(r=>key(r)===key(n));if(previous){map.delete(previous.id);map.set(n.id,normalize({...previous,...entry,id:n.id}))}else map.set(n.id,n)}return [...map.values()]}
function filter(rows,q){let result=rows.filter(r=>{if(q.view==='energy'&&!r.areas.some(a=>a==='Energy storage'||a==='Energy conversion'))return false;if(q.view==='due'&&!due(r))return false;if(q.view==='favorites'&&!r.favorite)return false;if(q.university&&r.university!==q.university)return false;if(q.area&&!r.areas.includes(q.area))return false;if(q.status&&r.status!==q.status)return false;const hay=[r.name,r.university,r.department,r.research,r.hook,r.notes,r.evidence,...r.areas].join(' ').toLowerCase();return (q.search||'').toLowerCase().split(/\s+/).filter(Boolean).every(x=>hay.includes(x))});const order=q.sort||'priority';return result.sort((a,b)=>{let n=0;if(order==='priority')n=(Number(a.priority)||9999)-(Number(b.priority)||9999);else if(order==='followup')n=(a.followup||'9999').localeCompare(b.followup||'9999');else if(order==='university')n=a.university.localeCompare(b.university);return n||a.name.localeCompare(b.name)})}
function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function escape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const api={statuses,replies,fields,csvAliases,key,normalize,validDate,today,due,parseCSV,fromCSV,stringifyCSV,merge,filter,safeURL,escape};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.TrackerCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
